# set -g default-terminal "tmux-256color"
# set -ag terminal-overrides ",xterm-255color:RGB"

##### --- POIMANDRES THEME START --- #####
# Status bar
set -g status on
set -g status-interval 5
set -g status-style "bg=#1b1e28,fg=#a6accd"

# Messages
set -g message-style "bg=#303340,fg=#e4f0fb"
set -g message-command-style "bg=#303340,fg=#add7ff"

# Panes Dividers
set -g pane-border-style "fg=#303340"
set -g pane-active-border-style "fg=#add7ff"

# Copy mode
setw -g mode-style "bg=#303340,fg=#e4f0fb"

# Window list
setw -g window-status-separator ""
setw -g window-status-style "bg=#1b1e28,fg=#a6accd"
setw -g window-status-current-style "bg=#303340,fg=#e4f0fb"

setw -g window-status-format "  #[fg=#a6accd]#I:#W  "
setw -g window-status-current-format "  #[fg=#add7ff]#I:#W  "

# Clock / bell
set -g clock-mode-colour "#add7ff"
set -g bell-action any
set -g visual-bell on

# Status left/right
set -g status-left-length 40
set -g status-right-length 80

set -g status-left  "#[fg=#add7ff]  #S "
set -g status-right "#[fg=#a6accd]%Y-%m-%d #[fg=#89ddff]%H:%M "
##### --- POIMANDRES THEME END --- #####

set -g allow-rename off
setw -g automatic-rename off

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

bind -r m resize-pane -Z

bind M-c attach-session -c "#{pane_current_path}"

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# Inactive pane border color
set -g pane-border-style fg=colour0
# Active pane border color
set -g pane-active-border-style fg=colour8

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
